### ISSUE TITLE
Reset presence settings after a while

### ISSUE THREAD

**Issue by AngeloCore** [PreMiD/Extension#200] opened 2022-01-11 09:19 UTC
### Description
The extension resets the settings to default after some time

### Operating System (OS)

Windows 11

### Browser

Brave

### Browser Version

Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

**Comment by Slowlife01** [comment] 2022-01-11 09:25
Duplicate of #195

**Closed** 2022-05-13 21:46 UTC
